# -*- coding: utf-8 -*-
"""Projeto_Unicornio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-dgyb7HAIeTJS6QgxCmp3G_WgzAFyXwH
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

Base_Dados = pd.read_csv('/content/unicorns till sep 2022.csv')

Base_Dados.shape

Base_Dados.head()

Base_Dados.rename( columns=
 {
   'Company': 'Empresa',
   'Valuation ($B)': 'Valor ($)',
   'Date Joined': 'Data de Adesão',
   'Country': 'Pais',
   'City': 'Cidade',
   'Industry': 'Setor',
   'Investors': 'Investidores',
 }, inplace=True
 )

Base_Dados.info()

Base_Dados.isnull().sum()

Base_Dados.nunique()

Base_Dados['Setor'].value_counts()

plt.figure(figsize=(15, 6))
plt.title('Analise de Setores')
plt.bar(Base_Dados['Setor'].value_counts().index, Base_Dados['Setor'].value_counts())
plt.xticks( rotation=45, ha='right');

Analise = round (Base_Dados['Pais'].value_counts(normalize=True) * 100, 1)

plt.figure(figsize=(15, 6))
plt.title('Analise dos Paises')
plt.pie(
    Analise.head(10),
    labels= Analise.index[0:10],
    shadow=True,
    startangle=90,
    autopct='%1.1f%%'
);

Base_Dados['Data de Adesão'] = pd.to_datetime( Base_Dados['Data de Adesão'])

Base_Dados['Data de Adesão'].head()

Base_Dados['Mes'] = pd.DatetimeIndex( Base_Dados['Data de Adesão']).month
Base_Dados['Ano'] = pd.DatetimeIndex( Base_Dados['Data de Adesão']).year

Base_Dados.head()

Analise_Agrupada = ( Base_Dados.groupby( by=['Pais', 'Ano', 'Mes', 'Empresa']).count().reset_index() )

Analise_Agrupada.loc[
    Analise_Agrupada ['Pais'] == 'Brazil'
].reset_index()

Base_Dados['Valor ($)'] = pd.to_numeric(Base_Dados['Valor ($)'].astype(str).str.replace('$', ''), errors='coerce')

Base_Dados.head()

Analise_Pais = Base_Dados.groupby (by=['Pais']).agg({'Valor ($)': 'sum'}).reset_index().sort_values('Valor ($)', ascending = False)

Analise_Pais.head(10).reset_index()

Analise_Valor = Analise_Pais.sort_values('Valor ($)', ascending=False)

Analise_Valor.head(10).reset_index()

plt.figure(figsize=(15, 6))
plt.title('Analise de Valor por Pais')
plt.plot (Analise_Valor['Pais'], Analise_Valor['Valor ($)'])
plt.xticks( rotation=45, ha='right');

